import "./Skills.scss";
const Skills = () => {
  return (
    <div className="skills">
      <div className="container">
        <div className="logos-slide">
          <img
            src="https://www.svgrepo.com/show/353925/javascript.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/374146/typescript-official.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354310/sass.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/355190/reactjs.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354431/tailwindcss-icon.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452228/html-5.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452185/css-3.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354521/vitejs.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354522/visual-studio-code.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373588/eslint2.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354119/nodejs-icon.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/355133/mysql.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452184/csharp.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373712/json.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354520/visual-studio.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/353935/jira.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/448221/docker.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452210/git.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/448226/gitlab.svg"
            alt=""
            loading="lazy"
          />
          <img src="/icons/Github.svg" alt="" loading="lazy" />
          <img
            src="https://www.svgrepo.com/show/354202/postman-icon.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373644/graphql.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354200/postgresql.svg"
            alt=""
            loading="lazy"
          />
        </div>
        <div className="logos-slide">
          <img
            src="https://www.svgrepo.com/show/353925/javascript.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/374146/typescript-official.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354310/sass.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/355190/reactjs.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354431/tailwindcss-icon.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452228/html-5.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452185/css-3.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354521/vitejs.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354522/visual-studio-code.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373588/eslint2.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354119/nodejs-icon.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/355133/mysql.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452184/csharp.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373712/json.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354520/visual-studio.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/353935/jira.svg"
            alt=""
            loading="lazy"
          />

          <img
            src="https://www.svgrepo.com/show/448221/docker.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/452210/git.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/448226/gitlab.svg"
            alt=""
            loading="lazy"
          />
          <img src="/icons/Github.svg" alt="" loading="lazy" />
          <img
            src="https://www.svgrepo.com/show/354202/postman-icon.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/373644/graphql.svg"
            alt=""
            loading="lazy"
          />
          <img
            src="https://www.svgrepo.com/show/354200/postgresql.svg"
            alt=""
            loading="lazy"
          />
        </div>
      </div>
    </div>
  );
};

export default Skills;
