name: SECURITY SCAN

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
 
jobs:
  snyk_scan:
    name: Análisis SCA con Snyk
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Instalar snyk
        run: npm install snyk -g

      - name: Ejecutar Snyk (análisis completo)
        id: snyk_run
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --json-file-output=snyk.json --sarif-file-output=snyk.sarif

      - name: Subir reportes Snyk como artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk.json
            snyk.sarif

      - name: Subir SARIF a Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
  sca_scan:
    name: SCAN Horusec
    runs-on: ubuntu-latest

    steps:
      - name: CLONING REPO
        uses: action/checkout@V3
  
      - name: RUN HORUSEC
        run:  docker run --name sast -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/src horuszup/horusec-cli:v2.7 horusec start -p /src -P $(pwd) || failure=truezsd